
#
# This file is the default set of rules to compile a Pebble project.
#
# Feel free to customize this to your needs.
#

import os.path

top = '.'
out = 'build'

def options(ctx):
    ctx.load('pebble_sdk')

def configure(ctx):
    ctx.load('pebble_sdk')
    gbitmap_tools_path = ctx.path.find_dir('../../delivery').abspath()
    ctx.check(stlib='gbitmap-tools', stlibpath=os.path.join(gbitmap_tools_path, "lib/aplite"), includes=os.path.join(gbitmap_tools_path, "include"), uselib_store='GBITMAP_TOOLS_APLITE')
    ctx.check(stlib='gbitmap-tools', stlibpath=os.path.join(gbitmap_tools_path, "lib/basalt"), includes=os.path.join(gbitmap_tools_path, "include"), uselib_store='GBITMAP_TOOLS_BASALT')

def build(ctx):
    ctx.load('pebble_sdk')

    build_worker = os.path.exists('worker_src')
    binaries = []

    for p in ctx.env.TARGET_PLATFORMS:

        print '---------- GBITMAP_TOOLS_' + str(p).upper()
        ctx.set_env(ctx.all_envs[p])
        ctx.set_group(ctx.env.PLATFORM_NAME)
        app_elf='{}/pebble-app.elf'.format(ctx.env.BUILD_DIR)
        ctx.pbl_program(source=ctx.path.ant_glob('src/**/*.c'),
        target=app_elf,
        use=['GBITMAP_TOOLS_' + str(p).upper()])

        if build_worker:
            worker_elf='{}/pebble-worker.elf'.format(ctx.env.BUILD_DIR)
            binaries.append({'platform': p, 'app_elf': app_elf, 'worker_elf': worker_elf})
            ctx.pbl_worker(source=ctx.path.ant_glob('worker_src/**/*.c'),
            target=worker_elf)
        else:
            binaries.append({'platform': p, 'app_elf': app_elf})

    ctx.set_group('bundle')
    ctx.pbl_bundle(binaries=binaries, js=ctx.path.ant_glob('src/js/**/*.js'))
